version: '3'
tasks:
  default:
    desc: 命令提示
    cmds:
      - task --list-all

  run:
    desc: 启动默认插件服务（当前为 SSH 插件）
    cmds:
      - task: run:ssh

  run:ssh:
    desc: 启动 SSH 插件服务
    cmds:
      - EGO_DEBUG=true go run plugins/ssh/cmd/main.go server

  gen:
    desc: 代码生成
    cmds:
      - buf generate api/proto

  mock:
    desc: 生成 Mock 代码
    cmds:
      - go generate ./...


