// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/ecmdb-plugins/ioc"
	"github.com/Duke1616/ecmdb-plugins/pkg/bootstrap"
)

// Injectors from wire.go:

func InitApp() (*bootstrap.PluginApp, error) {
	config := InitConfig()
	client := ioc.InitEtcdClient()
	registry := ioc.InitRegistry(client)
	resolver := InitResolverClient(registry)
	contextResolver := InitContextResolver(resolver)
	handler := InitSSHHandler(config, contextResolver)
	listener := InitListener(config)
	pluginApp := InitWebServer(config, handler, listener, resolver)
	return pluginApp, nil
}
