// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/ecmdb-plugins/ioc"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	v := InitGinMiddlewares()
	sdk := InitPolicySDK()
	syncer := InitPermSyncer()
	v2 := InitProviders()
	config := InitConfig()
	client := ioc.InitEtcdClient()
	registry := ioc.InitRegistry(client)
	resolver := InitResolverClient(registry)
	contextResolver := InitContextResolver(resolver)
	handler := InitSSHHandler(config, contextResolver)
	listener := InitListener(config)
	component := InitWebServer(v, sdk, syncer, v2, handler, listener)
	app := &App{
		Web:      component,
		Resolver: resolver,
	}
	return app, nil
}
