// Code generated by eiam permgen. DO NOT EDIT.

package permission

// Ssh 插件中心/SSH 插件
var Ssh = struct {
	Module        string
	Connect       string // 终端连接 [租户级]
	SftpArchive   string // 压缩文件 [租户级]
	SftpDelete    string // 删除文件 [租户级]
	SftpDownload  string // 下载文件 [租户级]
	SftpFiles     string // 查看文件 [租户级 · 静默]
	SftpMove      string // 移动文件 [租户级]
	SftpNewFile   string // 创建文件 [租户级]
	SftpNewFolder string // 创建目录 [租户级]
	SftpPreview   string // 预览文件 [租户级]
	SftpRename    string // 重命名文件 [租户级]
	SftpSave      string // 保存文件内容 [租户级]
	SftpSearch    string // 搜索文件 [租户级]
	SftpUnarchive string // 解压文件 [租户级]
	SftpUpload    string // 上传文件 [租户级]
	SftpUploadWs  string // 上传文件 [租户级]
	SshSession    string // 终端会话 [租户级 · 静默]
}{
	Module:        "cmdb:ssh",
	Connect:       "cmdb:ssh:connect",
	SftpArchive:   "cmdb:ssh:sftp_archive",
	SftpDelete:    "cmdb:ssh:sftp_delete",
	SftpDownload:  "cmdb:ssh:sftp_download",
	SftpFiles:     "cmdb:ssh:sftp_files",
	SftpMove:      "cmdb:ssh:sftp_move",
	SftpNewFile:   "cmdb:ssh:sftp_new_file",
	SftpNewFolder: "cmdb:ssh:sftp_new_folder",
	SftpPreview:   "cmdb:ssh:sftp_preview",
	SftpRename:    "cmdb:ssh:sftp_rename",
	SftpSave:      "cmdb:ssh:sftp_save",
	SftpSearch:    "cmdb:ssh:sftp_search",
	SftpUnarchive: "cmdb:ssh:sftp_unarchive",
	SftpUpload:    "cmdb:ssh:sftp_upload",
	SftpUploadWs:  "cmdb:ssh:sftp_upload_ws",
	SshSession:    "cmdb:ssh:ssh_session",
}
