// Code generated by eiam permgen. DO NOT EDIT.

package model

import "github.com/Duke1616/eiam/pkg/web/capability"

var (
	// Ssh 插件中心/SSH 插件 (cmdb:ssh)
	Ssh = capability.Model{
		Service: "cmdb",
		Name:    "ssh",
		Group:   "插件中心/SSH 插件",
		Scope:   capability.ScopeTenant,
	}
)
